esphome:
  name: test-device
  friendly_name: test device

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "X9RtIIgHYldfscUSD6k07+WGOokuhk3kD5qiBEgnFUs="

ota:
  - platform: esphome
    password: "ac943a9624235342c6b8734d284cd27b"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test-Device Fallback Hotspot"
    password: "nkfBOfOWA9W1"

captive_portal:
    