version: 4
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.1.63:1883
  user: homeassistant
  password: TF04IEA6MnPVIC
serial:
  baudrate: 115200
  rtscts: false
  port: >-
    /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2404939-if00
  adapter: deconz
advanced:
  log_level: info
  channel: 11
  network_key:
    - 200
    - 98
    - 48
    - 72
    - 104
    - 186
    - 44
    - 45
    - 150
    - 243
    - 33
    - 184
    - 105
    - 105
    - 43
    - 229
  pan_id: 7025
  ext_pan_id:
    - 62
    - 190
    - 123
    - 113
    - 218
    - 74
    - 35
    - 107
frontend:
  enabled: true
  port: 8099
homeassistant:
  enabled: true
devices:
  '0x2c1165fffeb66864':
    friendly_name: Ida tryckknapp
    description: Idas rum
  '0xb4e3f9fffe8929d7':
    friendly_name: Idas rullgardin
  '0x2c1165fffea5e438':
    friendly_name: Moa tryckknapp
  '0xb4e3f9fffef669f8':
    friendly_name: Moa rullgardin
  '0xb4e3f9fffe9f8222':
    friendly_name: Moa repeater
  '0xf84477fffe7c461f':
    friendly_name: Moa smartplug
  '0xd4fe28fffe2feda5':
    friendly_name: Ida smartplug
  '0xb4e3f9fffe936a09':
    friendly_name: Ida repeater
  '0x84b4dbfffe9719a6':
    friendly_name: Gästrum höger gardin
  '0x90395efffea5ef55':
    friendly_name: Gästrum tryckknapp
  '0x70ac08fffeb3d2d9':
    friendly_name: Gästrum vänster gardin
  '0x385b44fffefb5a2b':
    friendly_name: Gästrum repeater